// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBCQepQBp5boGKDa-4b8eqidNPjHOhjNE8",
    authDomain: "marnager-ecf30.firebaseapp.com",
    projectId: "marnager-ecf30",
    storageBucket: "marnager-ecf30.firebasestorage.app",
    messagingSenderId: "216614603367",
    appId: "1:216614603367:web:0cff121b396161d75322c2"
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05pLdrwrXpBdYO_HokL9J1LP3DF4jDcg',
    appId: '1:536957137727:web:7017133bfa4ac46af9598a',
    messagingSenderId: '536957137727',
    projectId: 'practico2-f3f38',
    authDomain: 'practico2-f3f38.firebaseapp.com',
    storageBucket: 'com.example.marnager',
  );

}
//// Import the functions you need from the SDKs you need
// import { initializeApp } from "firebase/app";
// // TODO: Add SDKs for Firebase products that you want to use
// // https://firebase.google.com/docs/web/setup#available-libraries

// // Your web app's Firebase configuration
// const firebaseConfig = {
//   apiKey: "AIzaSyBCQepQBp5boGKDa-4b8eqidNPjHOhjNE8",
//   authDomain: "marnager-ecf30.firebaseapp.com",
//   projectId: "marnager-ecf30",
//   storageBucket: "marnager-ecf30.firebasestorage.app",
//   messagingSenderId: "216614603367",
//   appId: "1:216614603367:web:0cff121b396161d75322c2"
// };

// // Initialize Firebase
// const app = initializeApp(firebaseConfig);